### ISSUE TITLE
Way to test alert sounds?

### ISSUE THREAD

**Issue by GeneralFriendly** [nnaaa-vr/XSOverlay-VRChat-Parser#13]
This is probably a me problem, but the Parser doesn't always make a sound when events trigger.  I'm using it standalone (only Oculus link, not using SteamVR/XSOverlay) in this case to get an audio alert mainly for portals being dropped and people joining and leaving.

I'm requesting a way to test fire an alert sound, so I can tell if audio is working.

I bounce the speaker device between the VR headset and the Main speakers.... and that is where I sometimes lose the audio.  

I guess I'm also asking for which device the Parser is using to be exposed.

Thanks

**Comment by nnaaa-vr** [comment]
Hi. The parser itself doesn't play audio, it relies on XSOverlay to play audio (the notification API supports sending a filesystem path to the audio file to play along with the notification). I've considered adding support for it to play via the parser instead when XSOverlay isn't running, but haven't done so as of yet. It's desirable to have XSOverlay handle the audio when it is running so that it can play the cue in sync with the notification displaying.

**Comment by GeneralFriendly** [comment]
Ah!  Thanks!    I'll just fire up XSOverlay, then, to get sounds.   Was confused that I had once heard them and then wasn't hearing them.   

I appreciate the response.
